# Generated by Django 5.0 on 2024-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.URLField(blank=True, verbose_name='Website address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip Code'),
        ),
    ]
