# Generated by Django 5.0 on 2024-07-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
